export const userData1 = {
    user: "Brian Bezos",
    transactions: [
      {
        user_id: "12395",
        total_orders: 30,
        last_order_date: "2024-08-04",
        average_spend_per_order: 25.5,
        loyalty_tier: "silvre",
        active_days: 30,
        status: "Completed",
      },
      {
        user_id: "67490",
        total_orders: 11,
        last_order_date: "2024-07-13",
        average_spend_per_order: 15.0,
        loyalty_tier: "silver",
        active_days: 13,
        status: "Completed",
      },
      {
        user_id: "32416",
        total_orders: 17,
        last_order_date: "2024-06-19",
        average_spend_per_order: 10.0,
        loyalty_tier: "bronze",
        active_days: 11,
        status: "Uncompleted",
      },
      {
        user_id: "53265",
        total_orders: 5,
        last_order_date: "2024-07-22",
        average_spend_per_order: 5.2,
        loyalty_tier: "bronze",
        active_days: 12,
        status: "Completed",
      },
      {
        user_id: "56724",
        total_orders: 13,
        last_order_date: "2024-07-23",
        average_spend_per_order: 17.2,
        loyalty_tier: "silver",
        active_days: 18,
        status: "Completed",
      },
      {
        user_id: "66549",
        total_orders: 15,
        last_order_date: "2024-07-24",
        average_spend_per_order: 16.2,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
      {
        user_id: "25648",
        total_orders: 17,
        last_order_date: "2024-07-26",
        average_spend_per_order: 20.2,
        loyalty_tier: "silver",
        active_days: 20,
        status: "Uncompleted",
      },
      {
        user_id: "94524",
        total_orders: 8,
        last_order_date: "2024-07-22",
        average_spend_per_order: 16.2,
        loyalty_tier: "bronze",
        active_days: 19,
        status: "Completed",
      },
    ],
  };
  