export var userData3 = {
    transactions: [
        {
            user_id: "12345",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 50,
            last_order_date: "2024-08-01",
            average_spend_per_order: 25.5,
            loyalty_tier: "gold",
            active_days: 30,
            status: "Completed",
          },
          {
            user_id: "53215",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 5,
            last_order_date: "2024-07-20",
            average_spend_per_order: 5.0,
            loyalty_tier: "bronze",
            active_days: 11,
            status: "Completed",
          },
          {
            user_id: "56324",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 12,
            last_order_date: "2024-07-19",
            average_spend_per_order: 17.0,
            loyalty_tier: "silver",
            active_days: 17,
            status: "Completed",
          },
          {
            user_id: "63249",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 13,
            last_order_date: "2024-07-21",
            average_spend_per_order: 16.0,
            loyalty_tier: "silver",
            active_days: 18,
            status: "Completed",
          },
          {
            user_id: "25468",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 19,
            last_order_date: "2024-07-25",
            average_spend_per_order: 20.0,
            loyalty_tier: "silver",
            active_days: 21,
            status: "Completed",
          },
          {
            user_id: "95324",
            username: "0001",
            user: "Brenda Banker",
            total_orders: 9,
            last_order_date: "2024-07-22",
            average_spend_per_order: 16.0,
            loyalty_tier: "silver",
            active_days: 18,
            status: "Completed",
          },
          {
            user_id: "12395",
            username: "0002",
            user: "Brian Bezos",
            total_orders: 30,
            last_order_date: "2024-08-04",
            average_spend_per_order: 25.5,
            loyalty_tier: "silvre",
            active_days: 30,
            status: "Completed",
          },
          {
            user_id: "53265",
            username: "0002",
            user: "Brian Bezos",
            total_orders: 5,
            last_order_date: "2024-07-22",
            average_spend_per_order: 5.2,
            loyalty_tier: "bronze",
            active_days: 12,
            status: "Completed",
          },
          {
            user_id: "56724",
            username: "0002",
            user: "Brian Bezos",
            total_orders: 13,
            last_order_date: "2024-07-23",
            average_spend_per_order: 17.2,
            loyalty_tier: "silver",
            active_days: 18,
            status: "Completed",
          },
          {
            user_id: "66549",
            username: "0002",
            user: "Brian Bezos",
            total_orders: 15,
            last_order_date: "2024-07-24",
            average_spend_per_order: 16.2,
            loyalty_tier: "silver",
            active_days: 19,
            status: "Completed",
          },
          {
            user_id: "94524",
            username: "0002",
            user: "Brian Bezos",
            total_orders: 8,
            last_order_date: "2024-07-22",
            average_spend_per_order: 16.2,
            loyalty_tier: "bronze",
            active_days: 19,
            status: "Completed",
          },
          {
            user_id: "13245",
            username: "0003",
            user: "Richard Rent",
            total_orders: 48,
            last_order_date: "2024-08-03",
            average_spend_per_order: 25.2,
            loyalty_tier: "gold",
            active_days: 28,
            status: "Completed",
          },
          {
            user_id: "61280",
            username: "0003",
            user: "Richard Rent",
            total_orders: 12,
            last_order_date: "2024-07-16",
            average_spend_per_order: 15.2,
            loyalty_tier: "silver",
            active_days: 17,
            status: "Completed",
          },
          {
            user_id: "25434",
            username: "0003",
            user: "Richard Rent",
            total_orders: 20,
            last_order_date: "2024-07-26",
            average_spend_per_order: 20.5,
            loyalty_tier: "silver",
            active_days: 23,
            status: "Completed",
          },
          {
            user_id: "68324",
            username: "0003",
            user: "Richard Rent",
            total_orders: 10,
            last_order_date: "2024-07-25",
            average_spend_per_order: 16.5,
            loyalty_tier: "silver",
            active_days: 19,
            status: "Completed",
          },
          {
            user_id: "34245",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 35,
            last_order_date: "2024-08-03",
            average_spend_per_order: 23.2,
            loyalty_tier: "gold",
            active_days: 28,
            status: "Completed",
          },
          {
            user_id: "62346",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 16,
            last_order_date: "2024-06-17",
            average_spend_per_order: 10.5,
            loyalty_tier: "bronze",
            active_days: 10,
            status: "Completed",
          },
          {
            user_id: "68224",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 5,
            last_order_date: "2024-07-22",
            average_spend_per_order: 5.2,
            loyalty_tier: "bronze",
            active_days: 13,
            status: "Completed",
          },
          {
            user_id: "89324",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 15,
            last_order_date: "2024-05-19",
            average_spend_per_order: 17.2,
            loyalty_tier: "silver",
            active_days: 19,
            status: "Completed",
          },
          {
            user_id: "20649",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 13,
            last_order_date: "2024-04-22",
            average_spend_per_order: 16.2,
            loyalty_tier: "silver",
            active_days: 11,
            status: "Completed",
          },
          {
            user_id: "61434",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 22,
            last_order_date: "2024-06-21",
            average_spend_per_order: 20.1,
            loyalty_tier: "silver",
            active_days: 23,
            status: "Completed",
          },
          {
            user_id: "24324",
            username: "0004",
            user: "Stacy Scholar",
            total_orders: 12,
            last_order_date: "2024-07-05",
            average_spend_per_order: 14.5,
            loyalty_tier: "silver",
            active_days: 16,
            status: "Completed",
          },
    ]
};