export const userData3 = {
    user: "Stacy Scholar",
    transactions: [
      {
        user_id: "34245",
        total_orders: 35,
        last_order_date: "2024-08-03",
        average_spend_per_order: 23.2,
        loyalty_tier: "gold",
        active_days: 28,
        status: "Completed",
      },
      {
        user_id: "46280",
        total_orders: 13,
        last_order_date: "2024-07-16",
        average_spend_per_order: 15.2,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
      {
        user_id: "62346",
        total_orders: 16,
        last_order_date: "2024-06-17",
        average_spend_per_order: 10.5,
        loyalty_tier: "bronze",
        active_days: 10,
        status: "Completed",
      },
      {
        user_id: "68224",
        total_orders: 5,
        last_order_date: "2024-07-22",
        average_spend_per_order: 5.2,
        loyalty_tier: "bronze",
        active_days: 13,
        status: "Completed",
      },
      {
        user_id: "89324",
        total_orders: 15,
        last_order_date: "2024-05-19",
        average_spend_per_order: 17.2,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
      {
        user_id: "20649",
        total_orders: 13,
        last_order_date: "2024-04-22",
        average_spend_per_order: 16.2,
        loyalty_tier: "silver",
        active_days: 11,
        status: "Completed",
      },
      {
        user_id: "61434",
        total_orders: 22,
        last_order_date: "2024-06-21",
        average_spend_per_order: 20.1,
        loyalty_tier: "silver",
        active_days: 23,
        status: "Completed",
      },
      {
        user_id: "24324",
        total_orders: 12,
        last_order_date: "2024-07-05",
        average_spend_per_order: 14.5,
        loyalty_tier: "silver",
        active_days: 16,
        status: "Completed",
      },
    ],
  };