export const userData = {
  user: "Brenda Banker",
  transactions: [
    {
      user_id: "12345",
      total_orders: 50,
      last_order_date: "2024-08-01",
      average_spend_per_order: 25.5,
      loyalty_tier: "gold",
      active_days: 30,
      status: "Completed",
    },
    {
      user_id: "67890",
      total_orders: 10,
      last_order_date: "2024-07-15",
      average_spend_per_order: 15.0,
      loyalty_tier: "silver",
      active_days: 15,
      status: "Completed",
    },
    {
      user_id: "32516",
      total_orders: 15,
      last_order_date: "2024-06-15",
      average_spend_per_order: 10.0,
      loyalty_tier: "bronze",
      active_days: 10,
      status: "Completed",
    },
    {
      user_id: "53215",
      total_orders: 5,
      last_order_date: "2024-07-20",
      average_spend_per_order: 5.0,
      loyalty_tier: "bronze",
      active_days: 11,
      status: "Completed",
    },
    {
      user_id: "56324",
      total_orders: 12,
      last_order_date: "2024-07-19",
      average_spend_per_order: 17.0,
      loyalty_tier: "silver",
      active_days: 17,
      status: "Completed",
    },
    {
      user_id: "63249",
      total_orders: 13,
      last_order_date: "2024-07-21",
      average_spend_per_order: 16.0,
      loyalty_tier: "silver",
      active_days: 18,
      status: "Completed",
    },
    {
      user_id: "25468",
      total_orders: 19,
      last_order_date: "2024-07-25",
      average_spend_per_order: 20.0,
      loyalty_tier: "silver",
      active_days: 21,
      status: "Completed",
    },
    {
      user_id: "95324",
      total_orders: 9,
      last_order_date: "2024-07-22",
      average_spend_per_order: 16.0,
      loyalty_tier: "silver",
      active_days: 18,
      status: "Completed",
    },
  ],
};
