export const userData2 = {
    user: "Richard Rent",
    transactions: [
      {
        user_id: "13245",
        total_orders: 48,
        last_order_date: "2024-08-03",
        average_spend_per_order: 25.2,
        loyalty_tier: "gold",
        active_days: 28,
        status: "Completed",
      },
      {
        user_id: "61280",
        total_orders: 12,
        last_order_date: "2024-07-16",
        average_spend_per_order: 15.2,
        loyalty_tier: "silver",
        active_days: 17,
        status: "Completed",
      },
      {
        user_id: "32346",
        total_orders: 17,
        last_order_date: "2024-06-17",
        average_spend_per_order: 10.3,
        loyalty_tier: "bronze",
        active_days: 10,
        status: "Uncompleted",
      },
      {
        user_id: "53224",
        total_orders: 5,
        last_order_date: "2024-07-22",
        average_spend_per_order: 5.2,
        loyalty_tier: "bronze",
        active_days: 13,
        status: "Completed",
      },
      {
        user_id: "64324",
        total_orders: 15,
        last_order_date: "2024-07-19",
        average_spend_per_order: 17.2,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
      {
        user_id: "62649",
        total_orders: 14,
        last_order_date: "2024-07-22",
        average_spend_per_order: 16.2,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
      {
        user_id: "25434",
        total_orders: 20,
        last_order_date: "2024-07-26",
        average_spend_per_order: 20.5,
        loyalty_tier: "silver",
        active_days: 23,
        status: "Completed",
      },
      {
        user_id: "68324",
        total_orders: 10,
        last_order_date: "2024-07-25",
        average_spend_per_order: 16.5,
        loyalty_tier: "silver",
        active_days: 19,
        status: "Completed",
      },
    ],
  };